# Generated by Django 4.2.7 on 2023-11-04 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "ToDo"),
                            (2, "Ongoing"),
                            (3, "Pending"),
                            (4, "Review"),
                            (5, "Done"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Created Time"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="tasks.user",
                    ),
                ),
            ],
        ),
    ]
